### ISSUE TITLE
Price issue in postgresql

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-headless#20]
Hi, 
i'm using postgresql whene i execute this comand line:
`php artisan aimeos:setup --option=setup/default/demo:1`

![image](https://github.com/user-attachments/assets/dc3ad11d-cbc3-4f88-b2f6-28b03bbd98f0)

thanks

**Comment by aimeos** [comment]
Can you post the complete stack trace please?

**Comment by MahmoudDevo** [comment]
Hi,
for a new setup, and empty postgresql :
`php artisan aimeos:setup --option=setup/default/demo:1`

`PS C:\laragon\www\bsahteck_complet> php artisan aimeos:setup --option=setup/default/demo:1
Initializing or updating the Aimeos database tables for site "default"
Migrating: \vendor\aimeos\aimeos-core\setup\AttributeMigrateKey.php
Migrated:  \vendor\aimeos\aimeos-core\setup\AttributeMigrateKey.php (633.26ms)
Migrating: \vendor\aimeos\aimeos-core\setup\TablesClearPropertyKey.php
Migrated:  \vendor\aimeos\aimeos-core\setup\TablesClearPropertyKey.php (26.24ms)
Migrating: \vendor\aimeos\aimeos-core\setup\IndexMigrateTextInnodb.php
Migrated:  \vendor\aimeos\aimeos-core\setup\IndexMigrateTextInnodb.php (28.97ms)
Migrating: \vendor\aimeos\ai-laravel\setup\TablesMigrateSiteidLaravel.php       
Migrated:  \vendor\aimeos\ai-laravel\setup\TablesMigrateSiteidLaravel.php (27.75ms)
Migrating: \vendor\aimeos\aimeos-core\setup\TablesMigrateSiteid.php
Migrated:  \vendor\aimeos\aimeos-core\setup\TablesMigrateSiteid.php (27.97ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Attribute.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Attribute.php (38.82ms)
Migrating: \vendor\aimeos\aimeos-core\setup\AttributeRemoveIndexes.php
Migrated:  \vendor\aimeos\aimeos-core\setup\AttributeRemoveIndexes.php (502.11ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CacheRemoveForeignkey.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CacheRemoveForeignkey.php (50.47ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CacheRemoveIndexes.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CacheRemoveIndexes.php (79.39ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Cache.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Cache.php (32.93ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Catalog.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Catalog.php (33.05ms)   
Migrating: \vendor\aimeos\aimeos-core\setup\CatalogRemoveIndexes.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CatalogRemoveIndexes.php (315ms)
Migrating: \vendor\aimeos\ai-cms-grapesjs\setup\Cms.php
Migrated:  \vendor\aimeos\ai-cms-grapesjs\setup\Cms.php (31.54ms)
Migrating: \vendor\aimeos\ai-cms-grapesjs\setup\CmsRemoveIndexes.php
Migrated:  \vendor\aimeos\ai-cms-grapesjs\setup\CmsRemoveIndexes.php (194.29ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CouponDropCodeForeign.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CouponDropCodeForeign.php (73.03ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CouponMigrateBasetValues.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CouponMigrateBasetValues.php (184.53ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CustomerDropAddressForeign.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CustomerDropAddressForeign.php (84.49ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Coupon.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Coupon.php (30.07ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CouponRemoveIndexes.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CouponRemoveIndexes.php (241.16ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerMigrateTableInnoDB.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerMigrateTableInnoDB.php (25.03ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerRemoveConstraints.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerRemoveConstraints.php (27.16ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CustomerRenameGroup.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CustomerRenameGroup.php (47.91ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerRenameGroupLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerRenameGroupLaravel.php (26ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Customer.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Customer.php (54.56ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Media.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Media.php (56.3ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Price.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Price.php (48.3ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Product.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Product.php (32.18ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerClearPropertyKeyLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerClearPropertyKeyLaravel.php (113.89ms)
Migrating: \vendor\aimeos\aimeos-core\setup\ServiceUniqueCode.php
Migrated:  \vendor\aimeos\aimeos-core\setup\ServiceUniqueCode.php (88.41ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Service.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Service.php (32.38ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Supplier.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Supplier.php (31.67ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Text.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Text.php (60.04ms)
Migrating: \vendor\aimeos\aimeos-core\setup\TablesMigrateListsKey.php
Migrated:  \vendor\aimeos\aimeos-core\setup\TablesMigrateListsKey.php (659.48ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerMigrateListsKeyLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerMigrateListsKeyLaravel.php (79.45ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerMigratePropertyKeyLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerMigratePropertyKeyLaravel.php (78.94ms)
Migrating: \vendor\aimeos\aimeos-core\setup\CustomerRemoveIndexes.php
Migrated:  \vendor\aimeos\aimeos-core\setup\CustomerRemoveIndexes.php (572.85ms)
Migrating: \vendor\aimeos\ai-laravel\setup\CustomerRemoveIndexesLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\CustomerRemoveIndexesLaravel.php (387.07ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Log.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Log.php (30.37ms)
Migrating: \vendor\aimeos\aimeos-core\setup\LocaleMigrateSite.php
Migrated:  \vendor\aimeos\aimeos-core\setup\LocaleMigrateSite.php (26.92ms)
Migrating: \vendor\aimeos\aimeos-core\setup\LocaleRemoveCharConstraints.php
Migrated:  \vendor\aimeos\aimeos-core\setup\LocaleRemoveCharConstraints.php (25.71ms)
Migrating: \vendor\aimeos\aimeos-core\setup\LocaleRenameSiteSupplier.php
Migrated:  \vendor\aimeos\aimeos-core\setup\LocaleRenameSiteSupplier.php (27.36ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Locale.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Locale.php (136.16ms)
Migrating: \vendor\aimeos\aimeos-core\setup\MShopAddLocaleLangCurData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\MShopAddLocaleLangCurData.php (293.22ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\MShopAddLocaleDataDefault.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\MShopAddLocaleDataDefault.php (29.05ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderAddProductParentid.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderAddProductParentid.php (25.29ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderConnectTables.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderConnectTables.php (26.04ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderRenameAttributeParentid.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderRenameAttributeParentid.php (28.8ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderRenameProductStatus.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderRenameProductStatus.php (25.54ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderRenameProductSupplier.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderRenameProductSupplier.php (76ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderRenameTables.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderRenameTables.php (265.41ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderRenameType.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderRenameType.php (26.65ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Order.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Order.php (60.15ms)
Migrating: \vendor\aimeos\aimeos-core\setup\OrderMergeBaseTable.php
Migrated:  \vendor\aimeos\aimeos-core\setup\OrderMergeBaseTable.php (24.61ms)
Migrating: \vendor\aimeos\aimeos-core\setup\MShopAddLocaleData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\MShopAddLocaleData.php (25.5ms)
Migrating: \vendor\aimeos\aimeos-core\setup\MShopSetLocale.php
Migrated:  \vendor\aimeos\aimeos-core\setup\MShopSetLocale.php (36.71ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddCatalogData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddCatalogData.php (571.96ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Group.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Group.php (30.65ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Plugin.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Plugin.php (35.87ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Rule.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Rule.php (31.77ms)
Migrating: \vendor\aimeos\aimeos-core\setup\StockMigrateProductId.php
Migrated:  \vendor\aimeos\aimeos-core\setup\StockMigrateProductId.php (93.54ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Stock.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Stock.php (31.42ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Tag.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Tag.php (31.17ms)
Migrating: \vendor\aimeos\aimeos-core\setup\MShopAddTypeData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\MShopAddTypeData.php (27.56ms)
Migrating: \vendor\aimeos\ai-cms-grapesjs\setup\default\MShopAddTypeDataCms.php
Migrated:  \vendor\aimeos\ai-cms-grapesjs\setup\default\MShopAddTypeDataCms.php (168.89ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddTypeData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddTypeData.php (54.41ms)
Migrating: \vendor\aimeos\ai-cms-grapesjs\setup\default\DemoAddCmsData.php
Migrated:  \vendor\aimeos\ai-cms-grapesjs\setup\default\DemoAddCmsData.php (101.83ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddCouponData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddCouponData.php (89.29ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\MShopAddTypeDataDefault.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\MShopAddTypeDataDefault.php (478.68ms)
Migrating: \vendor\aimeos\aimeos-core\setup\MShopAddCodeData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\MShopAddCodeData.php (24.29ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\MShopAddCodeDataDefault.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\MShopAddCodeDataDefault.php (65.43ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddCustomerData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddCustomerData.php (151.77ms)
Migrating: \vendor\aimeos\aimeos-core\setup\IndexRemoveIndexes.php
Migrated:  \vendor\aimeos\aimeos-core\setup\IndexRemoveIndexes.php (53.06ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Index.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Index.php (118.27ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddSupplierData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddSupplierData.php (123.43ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddProductData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddProductData.php (2107.82ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddServiceData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddServiceData.php (663.35ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddOrderData.php

   Aimeos\MShop\Price\Exception 

  Price can not be added. Currency ID "EUR" of price item and currently used currency ID "USD" does not match.

  at C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\src\MShop\Price\Item\Standard.php:437
    433▕        {
    434▕                if( $item->getCurrencyId() != $this->getCurrencyId() )
    435▕                {
    436▕                        $msg = 'Price can not be added. Currency ID "%1$s" of price item and currently used currency ID "%2$s" does 
not match.';
  ➜ 437▕                        throw new \Aimeos\MShop\Price\Exception( sprintf( $msg, $item->getCurrencyId(), $this->getCurrencyId() ) ); 
    438▕                }
    439▕
    440▕                if( $this === $item ) { $item = clone $item; }
    441▕                $taxValue = $this->getTaxValue(); // use initial value before it gets reset

  1   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\src\MShop\Order\Item\Base.php:1036
      Aimeos\MShop\Price\Item\Standard::addItem()

  2   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\src\MShop\Order\Item\Base.php:669
      Aimeos\MShop\Order\Item\Base::checkPrice()`

thanks

**Comment by aimeos** [comment]
Can you please execute `php artisan -vvv aimeos:setup --option=setup/default/demo:1`

**Comment by MahmoudDevo** [comment]
Hi,
After `php artisan -vvv aimeos:setup --option=setup/default/demo:1`

`...
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddSupplierData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddSupplierData.php (68.46ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddProductData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddProductData.php (2119.98ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddServiceData.php
Migrated:  \vendor\aimeos\aimeos-core\setup\default\DemoAddServiceData.php (560.73ms)
Migrating: \vendor\aimeos\aimeos-core\setup\default\DemoAddOrderData.php

   Aimeos\MShop\Price\Exception 

  Price can not be added. Currency ID "EUR" of price item and currently used currency ID "USD" does not match.

  at C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\src\MShop\Price\Item\Standard.php:437
    433▕        {
    434▕                if( $item->getCurrencyId() != $this->getCurrencyId() )
    435▕                {
    436▕                        $msg = 'Price can not be added. Currency ID "%1$s" of price item and currently used currency ID "%2$s" does 
not match.';
  ➜ 437▕                        throw new \Aimeos\MShop\Price\Exception( sprintf( $msg, $item->getCurrencyId(), $this->getCurrencyId() ) ); 
    438▕                }
    439▕
    440▕                if( $this === $item ) { $item = clone $item; }
    441▕                $taxValue = $this->getTaxValue(); // use initial value before it gets reset

  1   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\src\MShop\Order\Item\Base.php:1036
      Aimeos\MShop\Price\Item\Standard::addItem()

  2   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\src\MShop\Order\Item\Base.php:669
      Aimeos\MShop\Order\Item\Base::checkPrice()

  3   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\setup\default\DemoAddOrderData.php:94
      Aimeos\MShop\Order\Item\Base::addService()

  4   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\setup\default\DemoAddOrderData.php:49
      Aimeos\Upscheme\Task\DemoAddOrderData::addDemoData()

  5   C:\laragon\www\bsahteck_complet\vendor\aimeos\upscheme\src\Up.php:341
      Aimeos\Upscheme\Task\DemoAddOrderData::up()

  6   C:\laragon\www\bsahteck_complet\vendor\aimeos\upscheme\src\Up.php:172
      Aimeos\Upscheme\Up::runTasks()

  7   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-core\Setup.php:84
      Aimeos\Upscheme\Up::up()

  8   C:\laragon\www\bsahteck_complet\vendor\aimeos\aimeos-laravel\src\Command\SetupCommand.php:65
      Aimeos\Setup::up()

  9   C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Aimeos\Shop\Command\SetupCommand::handle()

  10  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Container\Util.php:41
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

  11  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:93
      Illuminate\Container\Util::unwrapIfClosure()

  12  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      Illuminate\Container\BoundMethod::callBoundMethod()

  13  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Container\Container.php:662
      Illuminate\Container\BoundMethod::call()

  14  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Console\Command.php:211
      Illuminate\Container\Container::call()

  15  C:\laragon\www\bsahteck_complet\vendor\symfony\console\Command\Command.php:326
      Illuminate\Console\Command::execute()

  16  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Console\Command.php:181
      Symfony\Component\Console\Command\Command::run()

  17  C:\laragon\www\bsahteck_complet\vendor\symfony\console\Application.php:1096
      Illuminate\Console\Command::run()

  18  C:\laragon\www\bsahteck_complet\vendor\symfony\console\Application.php:324
      Symfony\Component\Console\Application::doRunCommand()

  19  C:\laragon\www\bsahteck_complet\vendor\symfony\console\Application.php:175
      Symfony\Component\Console\Application::doRun()

  20  C:\laragon\www\bsahteck_complet\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:201
      Symfony\Component\Console\Application::run()

  21  C:\laragon\www\bsahteck_complet\artisan:37
      Illuminate\Foundation\Console\Kernel::handle()`

**Comment by aimeos** [comment]
Thanks for your report! The problem has been fixed and a new version is available. Run `composer up` and `php artisan aimeos:setup --options=setup/default/demo:1` or reinstall from scratch.

**Comment by MahmoudDevo** [comment]
Hi,
thank you for your replay, 
The problem not yet fixed, is the same 
I created a new postgresql db,
after `composer up`
 `php artisan config:cache;   php artisan cache:clear`
and `php artisan aimeos:setup --option=setup/default/demo:1` 

composer.json
`{
    "name": "aimeos/aimeos",
    "description": "Aimeos ecommerce and shop system",
    "keywords": ["aimeos", "ecommerce", "shop", "laravel", "distribution"],
    "license": "MIT",
    "type": "project",
    "repositories": [{
        "type": "composer",
        "url": "https://packages.aimeos.org/aimeoscom"
    }, {
        "type": "path",
        "url": "packages/*"
    }],
    "require": {
        "php": "^8.0.10",
        "aimeos/aimeos-laravel": "dev-master",
        "laravel/breeze": "*",
        "laravel/sanctum": "^3.3"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.15",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^10.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi",
            "App\\Composer::configure",
            "@php artisan migrate",
            "App\\Composer::setup",
            "App\\Composer::account",
            "App\\Composer::success"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan vendor:publish --tag=public --ansi --force"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by MahmoudDevo** [comment]
Hi,

The new `aimeos/aimeos-headless `setup works! Thank you.

However, I’m using a second folder (folder2) with `aimeos/aimeos-laravel` to add orders graphically in the same database. Unfortunately, after testing, it seems that the setup `php artisan aimeos:setup --option=setup/default/demo:1` in folder2 is not working as expected.

**Comment by aimeos** [comment]
Did you run `composer up` there too?

**Comment by MahmoudDevo** [comment]
Hi,
**Aimeos/aimeos-headless** works now , but when I connect **Aimeos/aimeos-laravel** to the same PostgreSQL database, it doesn't work.
